# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ecd615dc1c42d03346b5d33f45fb99bdb5fa677e029f617f07f877d6b6369fa87142a3e86dc9db015b37b831db0189944e093d6ce1c0de7f7d9567e52ec51040

test:
  secret_key_base: b3fd034590118f6b19f52a190252e987994c8d247a16bf96291ed71cbf80c334be0055288486a78a36385a123d177ef125a49c2939761c316d07a6d7c9dd8bc6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
